# Complete list of Perth metropolitan and major WA suburbs
# Used for autocomplete when adding a suburb to scrape

WA_SUBURBS = [
    "Alexander Heights", "Alfred Cove", "Alkimos", "Applecross", "Armadale",
    "Ascot", "Ashby", "Ashfield", "Attadale", "Atwell", "Aubin Grove",
    "Aveley", "Balcatta", "Baldivis", "Balga", "Ballajura", "Banksia Grove",
    "Bassendean", "Bayswater", "Beaconsfield", "Beckenham", "Bedford",
    "Bedfordale", "Beechboro", "Beldon", "Bellevue", "Belmont", "Bennett Springs",
    "Bentley", "Bertram", "Bibra Lake", "Bicton", "Booragoon", "Boya",
    "Brabham", "Brentwood", "Brigadoon", "Brookdale", "Brookton",
    "Bull Creek", "Bullsbrook", "Burns Beach", "Burswood", "Butler",
    "Byford", "Calista", "Canning Mills", "Canning Vale", "Cannington",
    "Carabooda", "Carine", "Carlisle", "Carmel", "Carnaby Rise",
    "Caversham", "Champion Lakes", "Churchlands", "City Beach",
    "Claremont", "Clarkson", "Cloverdale", "Cockburn Central", "Collie",
    "Como", "Connolly", "Coolbellup", "Coolbinia", "Cooloongup",
    "Cottesloe", "Craigie", "Crawley", "Cullacabardee", "Currambine",
    "Daglish", "Dalkeith", "Darch", "Darling Downs", "Darlington",
    "Dawesville", "Dayton", "Deanmill", "Dianella", "Doubleview",
    "Duncraig", "Dunsborough", "East Cannington", "East Fremantle",
    "East Perth", "East Victoria Park", "Eden Hill", "Edgewater",
    "Eglinton", "Ellenbrook", "Embleton", "Erskine", "Falcon",
    "Ferndale", "Floreat", "Forrestdale", "Forrestfield", "Fremantle",
    "Gidgegannup", "Girrawheen", "Glen Forrest", "Glendalough",
    "Gnangara", "Golden Bay", "Gooseberry Hill", "Gosnells",
    "Greenfields", "Greenwood", "Guildford", "Gwelup", "Hacketts Gully",
    "Halls Head", "Hamilton Hill", "Hammond Park", "Harrisdale",
    "Haynes", "Hazelmere", "Heathridge", "Helena Valley", "Henley Brook",
    "Herdsman", "Herne Hill", "High Wycombe", "Highgate", "Hilbert",
    "Hillarys", "Hillman", "Hilton", "Hocking", "Huntingdale",
    "Iluka", "Inglewood", "Innaloo", "Jandakot", "Jane Brook",
    "Jarrahdale", "Jolimont", "Joondalup", "Joondanna", "Kalamunda",
    "Karawara", "Kardinya", "Karnup", "Karrinyup", "Kelmscott",
    "Kenwick", "Kewdale", "Kiara", "Kings Park", "Kingsley",
    "Kinross", "Koondoola", "Koongamia", "Kwinana Town Centre",
    "Lakelands", "Langford", "Landsdale", "Lathlain", "Leda",
    "Leederville", "Leeming", "Lesmurdie", "Lockridge", "Lynwood",
    "Maddington", "Madeley", "Maida Vale", "Malaga", "Mandurah",
    "Mandogalup", "Manning", "Marangaroo", "Margaret River", "Marmion",
    "Martin", "Maylands", "Meadow Springs", "Medina", "Melville",
    "Menora", "Merriwa", "Middle Swan", "Midland", "Midvale",
    "Mindarie", "Mirrabooka", "Moondyne", "Mooney Mooney",
    "Morley", "Mosman Park", "Mount Claremont", "Mount Hawthorn",
    "Mount Helena", "Mount Lawley", "Mount Nasura", "Mount Pleasant",
    "Mount Richon", "Mullaloo", "Mundaring", "Mundijong", "Munster",
    "Murdoch", "Myaree", "Neerabup", "Nedlands", "Nollamara",
    "Noranda", "North Beach", "North Coogee", "North Fremantle",
    "North Lake", "North Perth", "Northam", "Northbridge",
    "Nowergup", "O'Connor", "Ocean Reef", "Oldbury", "Orange Grove",
    "Orelia", "Osborne Park", "Padbury", "Palmyra", "Parkerville",
    "Parkwood", "Parmelia", "Paulls Valley", "Pearsall", "Peppermint Grove",
    "Perth", "Piara Waters", "Pickering Brook", "Piedmont Park",
    "Port Kennedy", "Queens Park", "Quinns Rocks", "Ravenswood",
    "Redcliffe", "Riverton", "Rivervale", "Rockingham", "Roleystone",
    "Rossmoyne", "Rottnest Island", "Scarborough", "Seville Grove",
    "Shelley", "Shenton Park", "Shoalwater", "Serpentine",
    "Singleton", "Sorrento", "South Fremantle", "South Guildford",
    "South Lake", "South Perth", "Southern River", "Spearwood",
    "St James", "Stirling", "Stoneville", "Stratton", "Subiaco",
    "Success", "Swanbourne", "Swan View", "Sylvania", "Tapping",
    "The Vines", "Thornlie", "Treeby", "Trigg", "Tuart Hill",
    "Two Rocks", "Upper Swan", "Viveash", "Waikiki", "Walliston",
    "Wandi", "Wangara", "Wanneroo", "Warnbro", "Warwick",
    "Waterford", "Watermans Bay", "Wattle Grove", "Wellard",
    "Wembley", "Wembley Downs", "West Leederville", "West Perth",
    "West Swan", "Westminster", "White Gum Valley", "Whiteman",
    "Willagee", "Willetton", "Wilson", "Winthrop", "Woodbridge",
    "Woodlands", "Woodvale", "Wooroloo", "Wungong", "Yangebup",
    "Yanchep", "Yokine",
    # Regional WA
    "Albany", "Bunbury", "Busselton", "Geraldton", "Kalgoorlie",
    "Karratha", "Broome", "Port Hedland", "Esperance", "Carnarvon",
    "Exmouth", "Denmark", "Augusta", "Northam", "Toodyay",
    "York", "Mandurah", "Dawesville", "Falcon", "Halls Head",
    "Meadow Springs", "Pinjarra", "Waroona",
]

# Remove duplicates and sort
WA_SUBURBS = sorted(list(set(WA_SUBURBS)))


# Postcode lookup — Perth metro + agency-scope suburbs. Only entries the
# operator confirmed are listed here; everything else falls back to ''
# in the search response so the UI shows the suburb name without a
# misleading postcode. Add more keys as they're verified against
# Australia Post's official WA postcode list.
SUBURB_POSTCODES = {
    'Cottesloe': '6011',
    'Peppermint Grove': '6011',
    'Karrakatta': '6011',
    'Mosman Park': '6012',
    'Claremont': '6010',
    'Swanbourne': '6010',
    'Mount Claremont': '6010',
    'Nedlands': '6009',
    'Dalkeith': '6009',
    'Crawley': '6009',
    'Floreat': '6014',
    'Jolimont': '6014',
    'Wembley': '6014',
    'City Beach': '6015',
    'Wembley Downs': '6019',
    'Subiaco': '6008',
    'Daglish': '6008',
    'Shenton Park': '6008',
    'Leederville': '6007',
    'West Leederville': '6007',
    'North Perth': '6006',
    'Perth': '6000',
    'East Perth': '6004',
    'West Perth': '6005',
    'Fremantle': '6160',
    'North Fremantle': '6159',
    'South Fremantle': '6162',
    'East Fremantle': '6158',
    'Applecross': '6153',
    'Ardross': '6153',
    'Brentwood': '6153',
    'Mount Pleasant': '6153',
    'Attadale': '6156',
    'Bicton': '6157',
    'Booragoon': '6154',
}


def postcode_for(name):
    """Return the AU postcode for a suburb name, or '' when unknown.
    Case-insensitive lookup keyed on the WA_SUBURBS canonical name."""
    return SUBURB_POSTCODES.get((name or '').strip(), '')
