# Complete list of Perth metropolitan and major WA suburbs
# Used for autocomplete when adding a suburb to scrape

WA_SUBURBS = [
    "Alexander Heights", "Alfred Cove", "Alkimos", "Applecross", "Armadale",
    "Ascot", "Ashby", "Ashfield", "Attadale", "Atwell", "Aubin Grove",
    "Aveley", "Balcatta", "Baldivis", "Balga", "Ballajura", "Banksia Grove",
    "Bassendean", "Bayswater", "Beaconsfield", "Beckenham", "Bedford",
    "Bedfordale", "Beechboro", "Beldon", "Bellevue", "Belmont", "Bennett Springs",
    "Bentley", "Bertram", "Bibra Lake", "Bicton", "Booragoon", "Boya",
    "Brabham", "Brentwood", "Brigadoon", "Brookdale", "Brookton",
    "Bull Creek", "Bullsbrook", "Burns Beach", "Burswood", "Butler",
    "Byford", "Calista", "Canning Mills", "Canning Vale", "Cannington",
    "Carabooda", "Carine", "Carlisle", "Carmel", "Carnaby Rise",
    "Caversham", "Champion Lakes", "Churchlands", "City Beach",
    "Claremont", "Clarkson", "Cloverdale", "Cockburn Central", "Collie",
    "Como", "Connolly", "Coolbellup", "Coolbinia", "Cooloongup",
    "Cottesloe", "Craigie", "Crawley", "Cullacabardee", "Currambine",
    "Daglish", "Dalkeith", "Darch", "Darling Downs", "Darlington",
    "Dawesville", "Dayton", "Deanmill", "Dianella", "Doubleview",
    "Duncraig", "Dunsborough", "East Cannington", "East Fremantle",
    "East Perth", "East Victoria Park", "Eden Hill", "Edgewater",
    "Eglinton", "Ellenbrook", "Embleton", "Erskine", "Falcon",
    "Ferndale", "Floreat", "Forrestdale", "Forrestfield", "Fremantle",
    "Gidgegannup", "Girrawheen", "Glen Forrest", "Glendalough",
    "Gnangara", "Golden Bay", "Gooseberry Hill", "Gosnells",
    "Greenfields", "Greenwood", "Guildford", "Gwelup", "Hacketts Gully",
    "Halls Head", "Hamilton Hill", "Hammond Park", "Harrisdale",
    "Haynes", "Hazelmere", "Heathridge", "Helena Valley", "Henley Brook",
    "Herdsman", "Herne Hill", "High Wycombe", "Highgate", "Hilbert",
    "Hillarys", "Hillman", "Hilton", "Hocking", "Huntingdale",
    "Iluka", "Inglewood", "Innaloo", "Jandakot", "Jane Brook",
    "Jarrahdale", "Jolimont", "Joondalup", "Joondanna", "Kalamunda",
    "Karawara", "Kardinya", "Karnup", "Karrinyup", "Kelmscott",
    "Kenwick", "Kewdale", "Kiara", "Kings Park", "Kingsley",
    "Kinross", "Koondoola", "Koongamia", "Kwinana Town Centre",
    "Lakelands", "Langford", "Landsdale", "Lathlain", "Leda",
    "Leederville", "Leeming", "Lesmurdie", "Lockridge", "Lynwood",
    "Maddington", "Madeley", "Maida Vale", "Malaga", "Mandurah",
    "Mandogalup", "Manning", "Marangaroo", "Margaret River", "Marmion",
    "Martin", "Maylands", "Meadow Springs", "Medina", "Melville",
    "Menora", "Merriwa", "Middle Swan", "Midland", "Midvale",
    "Mindarie", "Mirrabooka", "Moondyne", "Mooney Mooney",
    "Morley", "Mosman Park", "Mount Claremont", "Mount Hawthorn",
    "Mount Helena", "Mount Lawley", "Mount Nasura", "Mount Pleasant",
    "Mount Richon", "Mullaloo", "Mundaring", "Mundijong", "Munster",
    "Murdoch", "Myaree", "Neerabup", "Nedlands", "Nollamara",
    "Noranda", "North Beach", "North Coogee", "North Fremantle",
    "North Lake", "North Perth", "Northam", "Northbridge",
    "Nowergup", "O'Connor", "Ocean Reef", "Oldbury", "Orange Grove",
    "Orelia", "Osborne Park", "Padbury", "Palmyra", "Parkerville",
    "Parkwood", "Parmelia", "Paulls Valley", "Pearsall", "Peppermint Grove",
    "Perth", "Piara Waters", "Pickering Brook", "Piedmont Park",
    "Port Kennedy", "Queens Park", "Quinns Rocks", "Ravenswood",
    "Redcliffe", "Riverton", "Rivervale", "Rockingham", "Roleystone",
    "Rossmoyne", "Rottnest Island", "Scarborough", "Seville Grove",
    "Shelley", "Shenton Park", "Shoalwater", "Serpentine",
    "Singleton", "Sorrento", "South Fremantle", "South Guildford",
    "South Lake", "South Perth", "Southern River", "Spearwood",
    "St James", "Stirling", "Stoneville", "Stratton", "Subiaco",
    "Success", "Swanbourne", "Swan View", "Sylvania", "Tapping",
    "The Vines", "Thornlie", "Treeby", "Trigg", "Tuart Hill",
    "Two Rocks", "Upper Swan", "Viveash", "Waikiki", "Walliston",
    "Wandi", "Wangara", "Wanneroo", "Warnbro", "Warwick",
    "Waterford", "Watermans Bay", "Wattle Grove", "Wellard",
    "Wembley", "Wembley Downs", "West Leederville", "West Perth",
    "West Swan", "Westminster", "White Gum Valley", "Whiteman",
    "Willagee", "Willetton", "Wilson", "Winthrop", "Woodbridge",
    "Woodlands", "Woodvale", "Wooroloo", "Wungong", "Yangebup",
    "Yanchep", "Yokine",
    # Regional WA
    "Albany", "Bunbury", "Busselton", "Geraldton", "Kalgoorlie",
    "Karratha", "Broome", "Port Hedland", "Esperance", "Carnarvon",
    "Exmouth", "Denmark", "Augusta", "Northam", "Toodyay",
    "York", "Mandurah", "Dawesville", "Falcon", "Halls Head",
    "Meadow Springs", "Pinjarra", "Waroona",
]

# Remove duplicates and sort
WA_SUBURBS = sorted(list(set(WA_SUBURBS)))


# Postcode lookup — Perth metro + major WA regional centres. Values
# verified against Australia Post's WA postcode list. Anything missing
# falls back to '' in the search response so the UI renders the suburb
# name alone rather than a misleading postcode.
SUBURB_POSTCODES = {
    # CBD / inner ring
    'Perth': '6000', 'East Perth': '6004', 'West Perth': '6005',
    'Northbridge': '6003', 'Highgate': '6003', 'North Perth': '6006',
    'Leederville': '6007', 'West Leederville': '6007',
    'Subiaco': '6008', 'Daglish': '6008', 'Shenton Park': '6008',
    'Nedlands': '6009', 'Dalkeith': '6009', 'Crawley': '6009',
    'Claremont': '6010', 'Swanbourne': '6010', 'Mount Claremont': '6010',
    'Karrakatta': '6011', 'Cottesloe': '6011', 'Peppermint Grove': '6011',
    'Mosman Park': '6012',
    'Floreat': '6014', 'Jolimont': '6014', 'Wembley': '6014',
    'City Beach': '6015', 'Mount Hawthorn': '6016', 'Glendalough': '6016',
    'Osborne Park': '6017', 'Innaloo': '6018', 'Doubleview': '6018',
    'Karrinyup': '6018', 'Gwelup': '6018', 'Scarborough': '6019',
    'Wembley Downs': '6019', 'Churchlands': '6018',
    'North Beach': '6020', 'Sorrento': '6020', 'Marmion': '6020',
    'Watermans Bay': '6020', 'Carine': '6020',
    'Balcatta': '6021', 'Stirling': '6021', 'Westminster': '6021',
    'Hamersley': '6022', 'Duncraig': '6023', 'Warwick': '6024',
    'Greenwood': '6024', 'Hillarys': '6025', 'Padbury': '6025',
    'Craigie': '6025', 'Kingsley': '6026', 'Woodvale': '6026',
    'Connolly': '6027', 'Edgewater': '6027', 'Heathridge': '6027',
    'Joondalup': '6027', 'Beldon': '6027', 'Mullaloo': '6027',
    'Ocean Reef': '6027', 'Currambine': '6028', 'Iluka': '6028',
    'Burns Beach': '6028', 'Kinross': '6028', 'Trigg': '6029',
    'Clarkson': '6030', 'Mindarie': '6030', 'Quinns Rocks': '6030',
    'Merriwa': '6030', 'Banksia Grove': '6031',
    'Eglinton': '6034', 'Yanchep': '6035', 'Butler': '6036',
    'Two Rocks': '6037', 'Alkimos': '6038',
    # Eastern
    'Maylands': '6051', 'Bedford': '6052', 'Inglewood': '6052',
    'Bayswater': '6053', 'Bassendean': '6054', 'Ashfield': '6054',
    'Eden Hill': '6054', 'Lockridge': '6054',
    'Guildford': '6055', 'South Guildford': '6055', 'Hazelmere': '6055',
    'Caversham': '6055', 'Dayton': '6055', 'Brabham': '6055',
    'Henley Brook': '6055', 'West Swan': '6055',
    'Midland': '6056', 'Midvale': '6056', 'Stratton': '6056',
    'Swan View': '6056', 'Jane Brook': '6056', 'Viveash': '6056',
    'Woodbridge': '6056', 'Bellevue': '6056', 'Boya': '6056',
    'Helena Valley': '6056', 'Herne Hill': '6056', 'Middle Swan': '6056',
    'Mount Lawley': '6050', 'Coolbinia': '6050', 'Menora': '6050',
    'Dianella': '6059', 'Tuart Hill': '6060', 'Yokine': '6060',
    'Joondanna': '6060', 'Nollamara': '6061', 'Mirrabooka': '6061',
    'Balga': '6061', 'Morley': '6062', 'Embleton': '6062',
    'Noranda': '6062', 'Beechboro': '6063',
    'Koondoola': '6064', 'Marangaroo': '6064', 'Girrawheen': '6064',
    'Alexander Heights': '6064',
    'Wanneroo': '6065', 'Madeley': '6065', 'Darch': '6065',
    'Landsdale': '6065', 'Pearsall': '6065', 'Ashby': '6065',
    'Hocking': '6065', 'Wangara': '6065', 'Gnangara': '6065',
    'Tapping': '6065',
    'Ballajura': '6066', 'Cullacabardee': '6066',
    'The Vines': '6069', 'Aveley': '6069', 'Ellenbrook': '6069',
    'Brigadoon': '6069', 'Upper Swan': '6069',
    'Darlington': '6070', 'Glen Forrest': '6071', 'Mundaring': '6073',
    'Mount Helena': '6082', 'Parkerville': '6081', 'Stoneville': '6081',
    'Gidgegannup': '6083', 'Bullsbrook': '6084',
    'Malaga': '6090',
    # South-east
    'Burswood': '6100', 'Lathlain': '6100',
    'East Victoria Park': '6101', 'Carlisle': '6101',
    'Bentley': '6102', 'St James': '6102',
    'Rivervale': '6103', 'Belmont': '6104', 'Ascot': '6104',
    'Redcliffe': '6104', 'Kewdale': '6105', 'Cloverdale': '6105',
    'Wattle Grove': '6107', 'Cannington': '6107', 'Beckenham': '6107',
    'Queens Park': '6107', 'East Cannington': '6107', 'Kenwick': '6107',
    'Wilson': '6107', 'Thornlie': '6108',
    'Maddington': '6109', 'Huntingdale': '6110', 'Gosnells': '6110',
    'Southern River': '6110', 'Kelmscott': '6111', 'Champion Lakes': '6111',
    'Roleystone': '6111', 'Armadale': '6112', 'Bedfordale': '6112',
    'Mount Nasura': '6112', 'Mount Richon': '6112', 'Forrestdale': '6112',
    'Haynes': '6112', 'Hilbert': '6112', 'Piara Waters': '6112',
    'Harrisdale': '6112', 'Brookdale': '6112',
    'Forrestfield': '6058', 'High Wycombe': '6057', 'Maida Vale': '6057',
    # South of river
    'South Perth': '6151', 'Como': '6152', 'Manning': '6152',
    'Karawara': '6152', 'Salter Point': '6152',
    'Applecross': '6153', 'Ardross': '6153', 'Brentwood': '6153',
    'Mount Pleasant': '6153',
    'Booragoon': '6154', 'Alfred Cove': '6154', 'Myaree': '6154',
    'Canning Vale': '6155', 'Willetton': '6155',
    'Attadale': '6156', 'Bicton': '6157',
    'East Fremantle': '6158', 'North Fremantle': '6159',
    'Fremantle': '6160', 'Beaconsfield': '6162',
    'South Fremantle': '6162', 'White Gum Valley': '6162',
    'Palmyra': '6157',
    'Hamilton Hill': '6163', 'Spearwood': '6163', 'Coolbellup': '6163',
    'Bibra Lake': '6163', "O'Connor": '6163', 'North Lake': '6163',
    'Kardinya': '6163',
    'Yangebup': '6164', 'Atwell': '6164', 'Aubin Grove': '6164',
    'Cockburn Central': '6164', 'Hammond Park': '6164', 'Success': '6164',
    'South Lake': '6164',
    'Bull Creek': '6149', 'Leeming': '6149', 'Murdoch': '6150',
    'Winthrop': '6150',
    'Ferndale': '6148', 'Riverton': '6148', 'Shelley': '6148',
    'Rossmoyne': '6148', 'Lynwood': '6147', 'Langford': '6147',
    'Parkwood': '6147',
    'Munster': '6166', 'Bertram': '6167', 'Calista': '6167',
    'Medina': '6167', 'Orelia': '6167', 'Parmelia': '6167',
    'Wandi': '6167', 'Mandogalup': '6167', 'Hillman': '6168',
    'Wellard': '6170', 'Leda': '6170',
    'Rockingham': '6168', 'Cooloongup': '6168', 'Shoalwater': '6169',
    'Warnbro': '6169', 'Waikiki': '6169',
    'Baldivis': '6171', 'Port Kennedy': '6172',
    'Singleton': '6175', 'Karnup': '6176', 'Golden Bay': '6174',
    'Lakelands': '6180',
    # Mandurah / peel
    'Mandurah': '6210', 'Halls Head': '6210', 'Erskine': '6210',
    'Greenfields': '6210', 'Meadow Springs': '6210',
    'Falcon': '6210', 'Dawesville': '6211',
    'Ravenswood': '6208', 'Waroona': '6215',
    # Hills + wider
    'Kalamunda': '6076', 'Lesmurdie': '6076', 'Walliston': '6076',
    'Gooseberry Hill': '6076', 'Carmel': '6076', 'Pickering Brook': '6076',
    'Mundijong': '6123', 'Byford': '6122', 'Serpentine': '6125',
    'Jandakot': '6164', 'Jarrahdale': '6124',
    # Regional WA
    'Albany': '6330', 'Bunbury': '6230', 'Busselton': '6280',
    'Geraldton': '6530', 'Kalgoorlie': '6430', 'Karratha': '6714',
    'Broome': '6725', 'Port Hedland': '6721', 'Esperance': '6450',
    'Carnarvon': '6701', 'Exmouth': '6707', 'Denmark': '6333',
    'Augusta': '6290', 'Northam': '6401', 'Toodyay': '6566',
    'York': '6302', 'Pinjarra': '6208', 'Margaret River': '6285',
    'Dunsborough': '6281',
}


def postcode_for(name):
    """Return the AU postcode for a suburb name, or '' when unknown.
    Case-insensitive lookup keyed on the WA_SUBURBS canonical name."""
    return SUBURB_POSTCODES.get((name or '').strip(), '')
