// Mirror of backend/wa_suburbs.py — kept in sync manually.
// Used by the sidebar autocomplete so the dropdown is instant
// instead of round-tripping through Render's free-tier API
// (which can cold-start and stall the dropdown for 30-60s).
// If you add a suburb here, add it to wa_suburbs.py as well.

export const WA_SUBURBS = [
  { name: "Albany", postcode: "6330" },
  { name: "Alexander Heights", postcode: "6064" },
  { name: "Alfred Cove", postcode: "6154" },
  { name: "Alkimos", postcode: "6038" },
  { name: "Applecross", postcode: "6153" },
  { name: "Armadale", postcode: "6112" },
  { name: "Ascot", postcode: "6104" },
  { name: "Ashby", postcode: "6065" },
  { name: "Ashfield", postcode: "6054" },
  { name: "Attadale", postcode: "6156" },
  { name: "Atwell", postcode: "6164" },
  { name: "Aubin Grove", postcode: "6164" },
  { name: "Augusta", postcode: "6290" },
  { name: "Aveley", postcode: "6069" },
  { name: "Balcatta", postcode: "6021" },
  { name: "Baldivis", postcode: "6171" },
  { name: "Balga", postcode: "6061" },
  { name: "Ballajura", postcode: "6066" },
  { name: "Banksia Grove", postcode: "6031" },
  { name: "Bassendean", postcode: "6054" },
  { name: "Bayswater", postcode: "6053" },
  { name: "Beaconsfield", postcode: "6162" },
  { name: "Beckenham", postcode: "6107" },
  { name: "Bedford", postcode: "6052" },
  { name: "Bedfordale", postcode: "6112" },
  { name: "Beechboro", postcode: "6063" },
  { name: "Beldon", postcode: "6027" },
  { name: "Bellevue", postcode: "6056" },
  { name: "Belmont", postcode: "6104" },
  { name: "Bennett Springs", postcode: "" },
  { name: "Bentley", postcode: "6102" },
  { name: "Bertram", postcode: "6167" },
  { name: "Bibra Lake", postcode: "6163" },
  { name: "Bicton", postcode: "6157" },
  { name: "Booragoon", postcode: "6154" },
  { name: "Boya", postcode: "6056" },
  { name: "Brabham", postcode: "6055" },
  { name: "Brentwood", postcode: "6153" },
  { name: "Brigadoon", postcode: "6069" },
  { name: "Brookdale", postcode: "6112" },
  { name: "Brookton", postcode: "" },
  { name: "Broome", postcode: "6725" },
  { name: "Bull Creek", postcode: "6149" },
  { name: "Bullsbrook", postcode: "6084" },
  { name: "Bunbury", postcode: "6230" },
  { name: "Burns Beach", postcode: "6028" },
  { name: "Burswood", postcode: "6100" },
  { name: "Busselton", postcode: "6280" },
  { name: "Butler", postcode: "6036" },
  { name: "Byford", postcode: "6122" },
  { name: "Calista", postcode: "6167" },
  { name: "Canning Mills", postcode: "" },
  { name: "Canning Vale", postcode: "6155" },
  { name: "Cannington", postcode: "6107" },
  { name: "Carabooda", postcode: "" },
  { name: "Carine", postcode: "6020" },
  { name: "Carlisle", postcode: "6101" },
  { name: "Carmel", postcode: "6076" },
  { name: "Carnaby Rise", postcode: "" },
  { name: "Carnarvon", postcode: "6701" },
  { name: "Caversham", postcode: "6055" },
  { name: "Champion Lakes", postcode: "6111" },
  { name: "Churchlands", postcode: "6018" },
  { name: "City Beach", postcode: "6015" },
  { name: "Claremont", postcode: "6010" },
  { name: "Clarkson", postcode: "6030" },
  { name: "Cloverdale", postcode: "6105" },
  { name: "Cockburn Central", postcode: "6164" },
  { name: "Collie", postcode: "" },
  { name: "Como", postcode: "6152" },
  { name: "Connolly", postcode: "6027" },
  { name: "Coolbellup", postcode: "6163" },
  { name: "Coolbinia", postcode: "6050" },
  { name: "Cooloongup", postcode: "6168" },
  { name: "Cottesloe", postcode: "6011" },
  { name: "Craigie", postcode: "6025" },
  { name: "Crawley", postcode: "6009" },
  { name: "Cullacabardee", postcode: "6066" },
  { name: "Currambine", postcode: "6028" },
  { name: "Daglish", postcode: "6008" },
  { name: "Dalkeith", postcode: "6009" },
  { name: "Darch", postcode: "6065" },
  { name: "Darling Downs", postcode: "" },
  { name: "Darlington", postcode: "6070" },
  { name: "Dawesville", postcode: "6211" },
  { name: "Dayton", postcode: "6055" },
  { name: "Deanmill", postcode: "" },
  { name: "Denmark", postcode: "6333" },
  { name: "Dianella", postcode: "6059" },
  { name: "Doubleview", postcode: "6018" },
  { name: "Duncraig", postcode: "6023" },
  { name: "Dunsborough", postcode: "6281" },
  { name: "East Cannington", postcode: "6107" },
  { name: "East Fremantle", postcode: "6158" },
  { name: "East Perth", postcode: "6004" },
  { name: "East Victoria Park", postcode: "6101" },
  { name: "Eden Hill", postcode: "6054" },
  { name: "Edgewater", postcode: "6027" },
  { name: "Eglinton", postcode: "6034" },
  { name: "Ellenbrook", postcode: "6069" },
  { name: "Embleton", postcode: "6062" },
  { name: "Erskine", postcode: "6210" },
  { name: "Esperance", postcode: "6450" },
  { name: "Exmouth", postcode: "6707" },
  { name: "Falcon", postcode: "6210" },
  { name: "Ferndale", postcode: "6148" },
  { name: "Floreat", postcode: "6014" },
  { name: "Forrestdale", postcode: "6112" },
  { name: "Forrestfield", postcode: "6058" },
  { name: "Fremantle", postcode: "6160" },
  { name: "Geraldton", postcode: "6530" },
  { name: "Gidgegannup", postcode: "6083" },
  { name: "Girrawheen", postcode: "6064" },
  { name: "Glen Forrest", postcode: "6071" },
  { name: "Glendalough", postcode: "6016" },
  { name: "Gnangara", postcode: "6065" },
  { name: "Golden Bay", postcode: "6174" },
  { name: "Gooseberry Hill", postcode: "6076" },
  { name: "Gosnells", postcode: "6110" },
  { name: "Greenfields", postcode: "6210" },
  { name: "Greenwood", postcode: "6024" },
  { name: "Guildford", postcode: "6055" },
  { name: "Gwelup", postcode: "6018" },
  { name: "Hacketts Gully", postcode: "" },
  { name: "Halls Head", postcode: "6210" },
  { name: "Hamilton Hill", postcode: "6163" },
  { name: "Hammond Park", postcode: "6164" },
  { name: "Harrisdale", postcode: "6112" },
  { name: "Haynes", postcode: "6112" },
  { name: "Hazelmere", postcode: "6055" },
  { name: "Heathridge", postcode: "6027" },
  { name: "Helena Valley", postcode: "6056" },
  { name: "Henley Brook", postcode: "6055" },
  { name: "Herdsman", postcode: "" },
  { name: "Herne Hill", postcode: "6056" },
  { name: "High Wycombe", postcode: "6057" },
  { name: "Highgate", postcode: "6003" },
  { name: "Hilbert", postcode: "6112" },
  { name: "Hillarys", postcode: "6025" },
  { name: "Hillman", postcode: "6168" },
  { name: "Hilton", postcode: "" },
  { name: "Hocking", postcode: "6065" },
  { name: "Huntingdale", postcode: "6110" },
  { name: "Iluka", postcode: "6028" },
  { name: "Inglewood", postcode: "6052" },
  { name: "Innaloo", postcode: "6018" },
  { name: "Jandakot", postcode: "6164" },
  { name: "Jane Brook", postcode: "6056" },
  { name: "Jarrahdale", postcode: "6124" },
  { name: "Jolimont", postcode: "6014" },
  { name: "Joondalup", postcode: "6027" },
  { name: "Joondanna", postcode: "6060" },
  { name: "Kalamunda", postcode: "6076" },
  { name: "Kalgoorlie", postcode: "6430" },
  { name: "Karawara", postcode: "6152" },
  { name: "Kardinya", postcode: "6163" },
  { name: "Karnup", postcode: "6176" },
  { name: "Karratha", postcode: "6714" },
  { name: "Karrinyup", postcode: "6018" },
  { name: "Kelmscott", postcode: "6111" },
  { name: "Kenwick", postcode: "6107" },
  { name: "Kewdale", postcode: "6105" },
  { name: "Kiara", postcode: "" },
  { name: "Kings Park", postcode: "" },
  { name: "Kingsley", postcode: "6026" },
  { name: "Kinross", postcode: "6028" },
  { name: "Koondoola", postcode: "6064" },
  { name: "Koongamia", postcode: "" },
  { name: "Kwinana Town Centre", postcode: "" },
  { name: "Lakelands", postcode: "6180" },
  { name: "Landsdale", postcode: "6065" },
  { name: "Langford", postcode: "6147" },
  { name: "Lathlain", postcode: "6100" },
  { name: "Leda", postcode: "6170" },
  { name: "Leederville", postcode: "6007" },
  { name: "Leeming", postcode: "6149" },
  { name: "Lesmurdie", postcode: "6076" },
  { name: "Lockridge", postcode: "6054" },
  { name: "Lynwood", postcode: "6147" },
  { name: "Maddington", postcode: "6109" },
  { name: "Madeley", postcode: "6065" },
  { name: "Maida Vale", postcode: "6057" },
  { name: "Malaga", postcode: "6090" },
  { name: "Mandogalup", postcode: "6167" },
  { name: "Mandurah", postcode: "6210" },
  { name: "Manning", postcode: "6152" },
  { name: "Marangaroo", postcode: "6064" },
  { name: "Margaret River", postcode: "6285" },
  { name: "Marmion", postcode: "6020" },
  { name: "Martin", postcode: "" },
  { name: "Maylands", postcode: "6051" },
  { name: "Meadow Springs", postcode: "6210" },
  { name: "Medina", postcode: "6167" },
  { name: "Melville", postcode: "" },
  { name: "Menora", postcode: "6050" },
  { name: "Merriwa", postcode: "6030" },
  { name: "Middle Swan", postcode: "6056" },
  { name: "Midland", postcode: "6056" },
  { name: "Midvale", postcode: "6056" },
  { name: "Mindarie", postcode: "6030" },
  { name: "Mirrabooka", postcode: "6061" },
  { name: "Moondyne", postcode: "" },
  { name: "Mooney Mooney", postcode: "" },
  { name: "Morley", postcode: "6062" },
  { name: "Mosman Park", postcode: "6012" },
  { name: "Mount Claremont", postcode: "6010" },
  { name: "Mount Hawthorn", postcode: "6016" },
  { name: "Mount Helena", postcode: "6082" },
  { name: "Mount Lawley", postcode: "6050" },
  { name: "Mount Nasura", postcode: "6112" },
  { name: "Mount Pleasant", postcode: "6153" },
  { name: "Mount Richon", postcode: "6112" },
  { name: "Mullaloo", postcode: "6027" },
  { name: "Mundaring", postcode: "6073" },
  { name: "Mundijong", postcode: "6123" },
  { name: "Munster", postcode: "6166" },
  { name: "Murdoch", postcode: "6150" },
  { name: "Myaree", postcode: "6154" },
  { name: "Nedlands", postcode: "6009" },
  { name: "Neerabup", postcode: "" },
  { name: "Nollamara", postcode: "6061" },
  { name: "Noranda", postcode: "6062" },
  { name: "North Beach", postcode: "6020" },
  { name: "North Coogee", postcode: "" },
  { name: "North Fremantle", postcode: "6159" },
  { name: "North Lake", postcode: "6163" },
  { name: "North Perth", postcode: "6006" },
  { name: "Northam", postcode: "6401" },
  { name: "Northbridge", postcode: "6003" },
  { name: "Nowergup", postcode: "" },
  { name: "O'Connor", postcode: "6163" },
  { name: "Ocean Reef", postcode: "6027" },
  { name: "Oldbury", postcode: "" },
  { name: "Orange Grove", postcode: "" },
  { name: "Orelia", postcode: "6167" },
  { name: "Osborne Park", postcode: "6017" },
  { name: "Padbury", postcode: "6025" },
  { name: "Palmyra", postcode: "6157" },
  { name: "Parkerville", postcode: "6081" },
  { name: "Parkwood", postcode: "6147" },
  { name: "Parmelia", postcode: "6167" },
  { name: "Paulls Valley", postcode: "" },
  { name: "Pearsall", postcode: "6065" },
  { name: "Peppermint Grove", postcode: "6011" },
  { name: "Perth", postcode: "6000" },
  { name: "Piara Waters", postcode: "6112" },
  { name: "Pickering Brook", postcode: "6076" },
  { name: "Piedmont Park", postcode: "" },
  { name: "Pinjarra", postcode: "6208" },
  { name: "Port Hedland", postcode: "6721" },
  { name: "Port Kennedy", postcode: "6172" },
  { name: "Queens Park", postcode: "6107" },
  { name: "Quinns Rocks", postcode: "6030" },
  { name: "Ravenswood", postcode: "6208" },
  { name: "Redcliffe", postcode: "6104" },
  { name: "Riverton", postcode: "6148" },
  { name: "Rivervale", postcode: "6103" },
  { name: "Rockingham", postcode: "6168" },
  { name: "Roleystone", postcode: "6111" },
  { name: "Rossmoyne", postcode: "6148" },
  { name: "Rottnest Island", postcode: "" },
  { name: "Scarborough", postcode: "6019" },
  { name: "Serpentine", postcode: "6125" },
  { name: "Seville Grove", postcode: "" },
  { name: "Shelley", postcode: "6148" },
  { name: "Shenton Park", postcode: "6008" },
  { name: "Shoalwater", postcode: "6169" },
  { name: "Singleton", postcode: "6175" },
  { name: "Sorrento", postcode: "6020" },
  { name: "South Fremantle", postcode: "6162" },
  { name: "South Guildford", postcode: "6055" },
  { name: "South Lake", postcode: "6164" },
  { name: "South Perth", postcode: "6151" },
  { name: "Southern River", postcode: "6110" },
  { name: "Spearwood", postcode: "6163" },
  { name: "St James", postcode: "6102" },
  { name: "Stirling", postcode: "6021" },
  { name: "Stoneville", postcode: "6081" },
  { name: "Stratton", postcode: "6056" },
  { name: "Subiaco", postcode: "6008" },
  { name: "Success", postcode: "6164" },
  { name: "Swan View", postcode: "6056" },
  { name: "Swanbourne", postcode: "6010" },
  { name: "Sylvania", postcode: "" },
  { name: "Tapping", postcode: "6065" },
  { name: "The Vines", postcode: "6069" },
  { name: "Thornlie", postcode: "6108" },
  { name: "Toodyay", postcode: "6566" },
  { name: "Treeby", postcode: "" },
  { name: "Trigg", postcode: "6029" },
  { name: "Tuart Hill", postcode: "6060" },
  { name: "Two Rocks", postcode: "6037" },
  { name: "Upper Swan", postcode: "6069" },
  { name: "Viveash", postcode: "6056" },
  { name: "Waikiki", postcode: "6169" },
  { name: "Walliston", postcode: "6076" },
  { name: "Wandi", postcode: "6167" },
  { name: "Wangara", postcode: "6065" },
  { name: "Wanneroo", postcode: "6065" },
  { name: "Warnbro", postcode: "6169" },
  { name: "Waroona", postcode: "6215" },
  { name: "Warwick", postcode: "6024" },
  { name: "Waterford", postcode: "" },
  { name: "Watermans Bay", postcode: "6020" },
  { name: "Wattle Grove", postcode: "6107" },
  { name: "Wellard", postcode: "6170" },
  { name: "Wembley", postcode: "6014" },
  { name: "Wembley Downs", postcode: "6019" },
  { name: "West Leederville", postcode: "6007" },
  { name: "West Perth", postcode: "6005" },
  { name: "West Swan", postcode: "6055" },
  { name: "Westminster", postcode: "6021" },
  { name: "White Gum Valley", postcode: "6162" },
  { name: "Whiteman", postcode: "" },
  { name: "Willagee", postcode: "" },
  { name: "Willetton", postcode: "6155" },
  { name: "Wilson", postcode: "6107" },
  { name: "Winthrop", postcode: "6150" },
  { name: "Woodbridge", postcode: "6056" },
  { name: "Woodlands", postcode: "" },
  { name: "Woodvale", postcode: "6026" },
  { name: "Wooroloo", postcode: "" },
  { name: "Wungong", postcode: "" },
  { name: "Yanchep", postcode: "6035" },
  { name: "Yangebup", postcode: "6164" },
  { name: "Yokine", postcode: "6060" },
  { name: "York", postcode: "6302" },
]

export function searchSuburbs(query, limit = 15) {
  const q = (query || '').trim().toLowerCase()
  if (!q) return []
  // Prefix matches first (matches REIWA's WA_SUBURBS search behaviour),
  // fall back to substring matches if there are no prefix hits.
  let matches = WA_SUBURBS.filter(s => s.name.toLowerCase().startsWith(q))
  if (matches.length === 0) {
    matches = WA_SUBURBS.filter(s => s.name.toLowerCase().includes(q))
  }
  return matches.slice(0, limit)
}
